import type { Metadata } from "next";
// import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        
        <main
            className={`
            grid grid-cols-12 gap-6 
            py-4 pt-16
            m-auto max-w-5xl w-full min-h-screen
        `}
        >
            <Navbar />
            <div className="col-span-9 col-start-4">{children}</div>
        </main>
    );
}
