import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={
                    openSans.className +
                `
                    bg-neutral-900
                    text-neutral-100  
                           
                    flex justify-center items-start
                `
                }
            >
{/* 
                <div className={`
                    h-80 w-full absolute top-0 left-0
                    bg-gradient-to-b from-[#C0B9DD] to-transparent
                `}></div> */}

                {/* <Navbar /> */}
                {children}
                <div
                aria-hidden="true"
                className="absolute top-16 inset-0 grid grid-cols-2 -space-x-52 opacity-10 pointer-events-none"
            >
                <div className="fix-safari-blur blur-[106px] h-96 bg-gradient-to-br from-violet-500 to-purple-400 dark:from-fuchsia-700"></div>
                <div className="fix-safari-blur blur-[106px] h-56 bg-gradient-to-r from-fuchsia-400 to-purple-300 dark:to-violet-600"></div>
                {/* <div className="fix-safari-blur blur-[106px] h-56 bg-gradient-to-r from-teal-400 to-indigo-800 dark:to-violet-600"></div>
                <div className="fix-safari-blur blur-[106px] h-56 bg-gradient-to-r from-green-500 to-rose-800 dark:to-violet-600"></div> */}
            </div>
            </body>
        </html>
    );
}
