import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={
                    openSans.className +
                `
                    bg-stone-200
                    text-stone-900  
                    mt-16          
                    flex justify-center items-start
                `
                }
            >
{/* 
                <div className={`
                    h-80 w-full absolute top-0 left-0
                    bg-gradient-to-b from-[#C0B9DD] to-transparent
                `}></div> */}

                <Navbar />
                {children}
            </body>
        </html>
    );
}
